import { router, useLocalSearchParams } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { acceptFriendInvitation } from "@/hooks/useFriends";
import { useAuth } from "@/providers/auth-provider";

/**
 * Invite accept screen.
 *
 * Deep link format:
 * - `pondrnative://invite/<token>` (generated by Linking.createURL)
 *
 * Behavior:
 * - If not authenticated, instruct user to log in first.
 * - If authenticated, accept invite and route to Friends tab.
 */
export default function InviteAcceptScreen() {
  const { token } = useLocalSearchParams<{ token?: string }>();
  const { user } = useAuth();

  const [isBusy, setIsBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!user) return;
    if (!token) return;

    let cancelled = false;
    async function run() {
      setIsBusy(true);
      setMessage(null);
      try {
        if (__DEV__) console.log("[invite] accepting", { token });
        await acceptFriendInvitation(token);
        if (cancelled) return;
        setMessage("Friend added.");
        router.replace("/(tabs)/friends");
      } catch (error) {
        console.error("[invite] accept failed", error);
        if (cancelled) return;
        setMessage(error instanceof Error ? error.message : "Failed to accept invite.");
      } finally {
        if (!cancelled) setIsBusy(false);
      }
    }

    void run();
    return () => {
      cancelled = true;
    };
  }, [token, user]);

  return (
    <SafeAreaView edges={["top"]} className="flex-1 bg-background px-4 pt-10">
      <Text className="font-display text-3xl text-foreground">Invitation</Text>
      <Text className="mt-2 font-mono text-xs uppercase tracking-wider text-muted-foreground">
        {token ? "Accepting invite…" : "Missing token"}
      </Text>

      {!user ? (
        <View className="mt-8 gap-4">
          <Text className="font-body text-base text-foreground">Log in to accept this invite.</Text>
          <Pressable
            onPress={() => router.replace("/(auth)/login")}
            className="items-center justify-center rounded-xl bg-primary px-4 py-3"
          >
            <Text className="font-mono text-xs uppercase tracking-wider text-background">Go to login</Text>
          </Pressable>
        </View>
      ) : (
        <View className="mt-8 gap-4">
          {isBusy ? <ActivityIndicator /> : null}
          {!!message ? <Text className="font-mono text-xs text-muted-foreground">{message}</Text> : null}
        </View>
      )}
    </SafeAreaView>
  );
}




